DB_USERNAME: root
DB_URL: jdbc:mysql://j10e105.p.ssafy.io:3306/ggame
DB_PASSWORD: GGAME!buk105
SERVER_PORT: 8000
OAUTH_CLIENT_ID: 101986713723-q17fdcl43u2atuf4ce62gqcjp4hvn4l1.apps.googleusercontent.com
OAUTH_CLIENT_SECRET: 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
OAUTH_CLIENT_SCOPE: profile, email
OAUTH_URL: https://j10e105.p.ssafy.io/api/auth/google/callback
CASSANDRA_KEYSPACE: ggame
CASSANDRA_CONTACT_POINTS: j10e105.p.ssafy.io
CASSANDRA_PORT: 9042


CHROME_DRIVER_PATH: src/main/resources/chromedriver-win64/chromedriver.exe
