spring:
  profiles:
    active: env
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: 'true'
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            scope: ${OAUTH_CLIENT_SCOPE}
  cassandra:
    keyspace-name: ${CASSANDRA_KEYSPACE}
    contact-points: ${CASSANDRA_CONTACT_POINTS}
    port: ${CASSANDRA_PORT}
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
server:
  port: ${SERVER_PORT}

selenium:
    driver: ${CHROME_DRIVER_PATH}
